OpenLoyalty\Component\Campaign\Domain\Campaign:
  type: entity
  repositoryClass: OpenLoyalty\Component\Campaign\Infrastructure\Persistence\Doctrine\Repository\DoctrineCampaignRepository
  table: ol__campaign
  id:
    campaignId:
      type: campaign_id
      column: campaign_id
  fields:
    reward:
      type: string
    name:
      type: string
    shortDescription:
      type: text
      nullable: true
      column: short_description
    moreInformationLink:
      type: text
      nullable: true
      column: more_information_link
    conditionsDescription:
      type: text
      nullable: true
      column: conditions_description
    usageInstruction:
      type: text
      nullable: true
      column: usage_instruction
    brandDescription:
      type: text
      nullable: true
      column: brand_description
    active:
      type: boolean
      options:
        default: 0
    pointValue:
      type: decimal
      scale: 2
      precision: 14
      nullable: true
    costInPoints:
      type: decimal
      scale: 2
      precision: 14
      column: cost_in_points
    levels:
      type: campaign_levels_json_array
    segments:
      type: campaign_segments_json_array
    unlimited:
      type: boolean
      options:
        default: 1
    singleCoupon:
      type: boolean
      options:
        default: 1
    limit:
      type: integer
      nullable: true
      column: usage_limit
    limitPerUser:
      type: integer
      nullable: true
      column: limit_per_user
    coupons:
      type: campaign_coupons_json_array
    rewardValue:
      type: decimal
      scale: 2
      precision: 14
      nullable: true
      column: reward_value
    tax:
      type: integer
      nullable: true
      column: tax
    taxPriceValue:
      type: decimal
      scale: 2
      precision: 14
      nullable: true
      column: tax_price_value
    labels:
      type: labels_json_array
      column: labels
      nullable: true
    brandName:
      type: text
      nullable: true
      column: brand_name
    daysInactive:
      type: integer
      nullable: true
      column: days_inactive
    daysValid:
      type: integer
      nullable: true
      column: daysValid
    transactionPercentageValue:
      type: integer
      nullable: true
      column: transaction_percentage_value
    categories:
      type: campaign_categories_json_array
      nullable: true
    featured:
      type: boolean
      options:
        default: 1
  embedded:
    campaignActivity:
      class: OpenLoyalty\Component\Campaign\Domain\Model\CampaignActivity
    campaignVisibility:
      class: OpenLoyalty\Component\Campaign\Domain\Model\CampaignVisibility
    campaignPhoto:
      class: OpenLoyalty\Component\Campaign\Domain\Model\CampaignPhoto
    brandIcon:
      class: OpenLoyalty\Component\Campaign\Domain\Model\CampaignBrandIcon

